### ISSUE TITLE
Roadmap to 1.2

### ISSUE THREAD

**Issue by iStefo** [iStefo/ember-select-2#32]
This issue will collect and keep track of upcoming features I would like to have in the 1.2 release, which will probably published in January 2015.

- [ ] Tests for ember-i18n support (#28)
- [x] Adding option to disable the search field for single select dropdowns (#29)
- [x] Fix promises in value binding (#30)
- [x] Make $.fn.select2 assertion compatible with ember 1.10 (#34)
- [ ] ... probably more to come as I am able to process more tickets

**Comment by iStefo** [comment]
Since such a long time has passed, it's time for 1.2 to finally ship. Many additions made it into the addon, ember-i18n support unfortunately hasn't and will be moved to a new issue
